import{a as q,S as P,i as u}from"./assets/vendor-BfxZYtf8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const $="https://pixabay.com/api/",E="54245277-1c637348af7f3e854ea758d9c";async function L(t,o){const n={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get($,{params:n})).data}let a=null;const d=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=document.querySelector(".load-more");c?c.classList.add("is-hidden"):console.warn("Loader element not found: .loader");function M(){a||(a=new P(".gallery a",{captionsData:"alt",captionDelay:250}))}function w(t){if(!d)return;const o=t.map(n=>{const s=(n.tags||"Image").split(",")[0].trim(),e=B(n.views),r=n.user||"CREATOR";return`
      <li class="gallery-item" role="listitem">
        <a class="gallery-link" href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${m(n.tags)}" loading="lazy" />
        </a>
        <div class="info">
          <h3 class="info-title">${m(s)}</h3>
          <div class="info-meta">
            <span class="info-views">${e} views</span>
            <span class="info-creator">${m(r)}</span>
          </div>
          <div class="info-stats">
            <span><b>Likes:</b> ${n.likes}</span>
            <span><b>Comments:</b> ${n.comments}</span>
            <span><b>Downloads:</b> ${n.downloads}</span>
          </div>
        </div>
      </li>`}).join("");d.insertAdjacentHTML("beforeend",o),M(),a&&typeof a.refresh=="function"&&a.refresh()}function x(){d&&(d.innerHTML="",a&&typeof a.refresh=="function"&&a.refresh())}function b(){c&&c.classList.remove("is-hidden")}function v(){c&&c.classList.add("is-hidden")}function B(t=0){return t>=1e6?(t/1e6).toFixed(1).replace(/\.0$/,"")+"M":t>=1e3?(t/1e3).toFixed(1).replace(/\.0$/,"")+"K":String(t)}function m(t=""){return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _(){f&&f.classList.remove("is-hidden")}function S(){f&&f.classList.add("is-hidden")}let i=1,h="",p=0;const g=document.querySelector(".form");g?g.addEventListener("submit",I):console.warn("Form element not found: .form");async function I(t){t.preventDefault();const o=t.currentTarget,s=o.elements["search-text"].value.trim();if(s===""){u.error({message:"Please enter a search query!"});return}h=s,i=1,o.reset(),x(),S(),b();try{const e=await L(h,i);p=e.totalHits||0;const r=e.hits||[];if(r.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}w(r);const l=Math.ceil(p/15);i<l&&_()}catch(e){console.error(e),u.error({message:"Something went wrong. Please try again later."})}finally{v()}}const y=document.querySelector(".load-more");y?y.addEventListener("click",O):console.warn("Load more button not found: .load-more");async function O(){i+=1,b();try{const o=(await L(h,i)).hits||[];w(o),i*15>=p&&(S(),u.info({message:"We're sorry, but you've reached the end of search results."})),R()}catch(t){console.error(t),u.error({message:"Something went wrong. Please try again later."})}finally{v()}}function R(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
